# Generated by Django 2.0 on 2019-04-02 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuida24', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('AF', 'Atividade Fisica'), ('LS', 'Lazer Social'), ('LI', 'Lazer Individual')], max_length=2)),
                ('atividadeEspecifica', models.TextField(blank=True, null=True)),
                ('duracao', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Constituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimento', models.CharField(choices=[('CB', 'Carnes Brancas'), ('FT', 'Fruta'), ('VG', 'Vegetais'), ('FB', 'Fibras'), ('PC', 'Pré-cozinhados'), ('RF', 'Refrigerantes'), ('AL', 'Alcool')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DefAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('local', models.TextField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuida24.DefAtividade')),
            ],
        ),
        migrations.CreateModel(
            name='LazerIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuida24.DefAtividade')),
            ],
        ),
        migrations.CreateModel(
            name='LazerSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuida24.DefAtividade')),
            ],
        ),
        migrations.CreateModel(
            name='Medicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('estado', models.CharField(choices=[('E', 'Experimental'), ('A', 'Ativo'), ('I', 'Inativo')], max_length=2)),
                ('detalhes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuida24.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsAtiva', models.TextField()),
                ('nome', models.TextField()),
                ('formaFarmaceutica', models.TextField()),
                ('dosagem', models.IntegerField()),
                ('titular', models.TextField()),
                ('generico', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NotaConsulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField()),
                ('categoria', models.CharField(choices=[('ENF', 'Enfermagem'), ('CLI', 'Clinica'), ('PSI', 'Psicologia'), ('OTR', 'Outras Apreciações')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateField()),
                ('hora', models.TimeField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuida24.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='ParamAnaliticos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuida24.Cuidador')),
            ],
        ),
        migrations.CreateModel(
            name='ParamFisiologicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuida24.Cuidador')),
            ],
        ),
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('realizado', models.BooleanField()),
                ('tipo', models.CharField(choices=[('PA', 'Pequeno Almoço'), ('LM', 'Lanche Manhã'), ('AL', 'Almoço'), ('LT', 'LancheTarde'), ('JT', 'Jantar')], max_length=2)),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuida24.Cuidador')),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.TextField()),
                ('tipo', models.CharField(choices=[('I', 'Individual'), ('G', 'Grupo')], max_length=1)),
                ('descricao', models.TextField()),
                ('objetivo', models.TextField()),
                ('material', models.TextField()),
                ('estado', models.CharField(choices=[('E', 'Espera'), ('A', 'Aceite'), ('R', 'Revisao'), ('C', 'Concluida')], max_length=1)),
                ('detalhes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuida24.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Sestas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidade', models.IntegerField()),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuida24.Cuidador')),
            ],
        ),
        migrations.CreateModel(
            name='Sono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('qualidade', models.BooleanField()),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuida24.Cuidador')),
            ],
        ),
        migrations.CreateModel(
            name='Tomas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('medicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuida24.Medicacao')),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuida24.Cuidador')),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UtilizadorBackoffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ADM', 'Administrador'), ('COR', 'Coordenador'), ('REM', 'Responsável Medicação'), ('PRF', 'Profissional Saúde'), ('MED', 'Médico'), ('ENF', 'Enfermeiro'), ('PSI', 'Psicólogo')], max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='prescricao',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuida24.UtilizadorBackoffice'),
        ),
        migrations.AddField(
            model_name='prescricao',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuida24.Utente'),
        ),
        migrations.AddField(
            model_name='notaconsulta',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuida24.UtilizadorBackoffice'),
        ),
        migrations.AddField(
            model_name='notaconsulta',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuida24.Consulta'),
        ),
        migrations.AddField(
            model_name='medicacao',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuida24.Medicamento'),
        ),
        migrations.AddField(
            model_name='medicacao',
            name='prescricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuida24.Prescricao'),
        ),
        migrations.AddField(
            model_name='constituicao',
            name='refeicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuida24.Refeicao'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='cuidador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuida24.Cuidador'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='sessao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuida24.Sessao'),
        ),
        migrations.AddField(
            model_name='atividadefisica',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuida24.DefAtividade'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='cuidador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuida24.Cuidador'),
        ),
        migrations.AddField(
            model_name='agua',
            name='cuidador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuida24.Cuidador'),
        ),
    ]
